name: Node Build and Deploy
on:
  push:
    branches:
      - 'dev-*'
    tags:
      - 'v*'
    paths:
      - '**.js'
      - '.ci/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/*.yaml'
      - 'config/*'

defaults:
  run:
    shell: bash

jobs:  
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      target-environment: ${{ steps.reference-check.outputs.TARGET_ENVIRONMENT }}
    steps:
      - name: Reference check
        id: reference-check
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          if [[ $GITHUB_REF_NAME == dev-*]]; then
            echo "Setting TARGET_ENVIRONMENT to development"
            echo "TARGET_ENVIRONMENT=development" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF_NAME == v*]]; then
            echo "Setting TARGET_ENVIRONMENT to production"
            echo "TARGET_ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "Setting TARGET_ENVIRONMENT to false"
            echo "TARGET_ENVIRONMENT=false" >> $GITHUB_OUTPUT
          fi

# ----------------------------- #

  aws-deploy-dev:
    if: needs.determine-environment.outputs.target-environment
    needs: determine-environment
    uses: ./.github/workflows/workflow-aws-deploy.yaml
    secrets: inherit
    with: 
      environment-name: ${{ needs.determine-environment.outputs.target-environment }}
