name: Deploy Slash Commands to Discord
on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  discord-slash-deploy:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.environment-name }}

    name: Deploy Slash Commands to Discord
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Run npm install
        run: npm i --only=prod

      - name: zip up the folder
        run: npm run build

      - name: Execute slash-command installer
        run: |
          cd commands/
          node index.js
        env:
          DISCORD_BOT_APP_ID: ${{ secrets.DISCORD_BOT_APP_ID }}
          TARGET_GUILD_ID: ${{ secrets.TARGET_GUILD_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
