on:
  push:
    branches-ignore:
      - 'main'

defaults:
  run:
    shell: bash


jobs:
  npm-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
  
    env:
      FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
      LAMBDA_EXECUTION_ROLE: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}
      LAMBDA_ENV_VARS: |
        ${{ join(fromJSON('["DISCORD_BOT_PUBLIC_KEY=join1",
              "DISCORD_BOT_TOKEN=join2",
              "POSTMAN_VERIFY=join3",
              "VERSION=SOME_VERSION+SHA"]')) }}

    name: What is the variable
    steps:
      - name: echo LAMBDA_ENV_VARS
        run: echo ${LAMBDA_ENV_VARS}